### ISSUE TITLE
Support Version for China Region

### ISSUE THREAD

**Issue by ZenoRewn** [aws-solutions/machine-downtime-monitor-on-aws#1]
**Describe the feature you'd like**
machine downtime monitor is useful.
but it can't work in aws china region.
can you guys create an version for china aws region?

Thanks

**Comment by ericquinones** [comment]
Hi @ZenoRewn -

Thank you for reaching out. To help us research, can you please let us know the issues you're having that's preventing you from launching the solution? Is there an error you are seeing in the CloudFormation event logs?
