### ISSUE TITLE
QuickSight integration fails

### ISSUE THREAD

**Issue by ShutoAraki** [aws-solutions/machine-downtime-monitor-on-aws#3]
**Describe the bug**
When I enter my QuickSight Principal ARN, the CFn Stack fails to create resources.

It works fine when I choose not to do it.

**To Reproduce**
I got my QuickSight Principal ARN the following way:

First, get my namespace: `aws quicksight list-namespaces --aws-account-id 123456789`

And then, I got my Principal ARN: `aws quicksight list-users --region us-east-1 --aws-account-id 123456789 --namespace <whatever I got from the previous command>`

**Expected behavior**

The CFn template should work with the way I fetch the QuickSight Principal ARN.

**Please complete the following information about the solution:**
- [x] Version: [e.g. v1.0.0]
- [x] Region: [e.g. us-east-1]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**

**Additional context**

**Comment by gattasrikanth** [comment]
Can you please update what is the error message that you are seeing when the Cloudformation Stack deployment fails. Also provide if there is any additional information from CloudWatch logs.

**Comment by ShutoAraki** [comment]
This is the CloudFormation error:
```
The following resource(s) failed to create: [BIReportingEtlGlueConvertParquetJobTriggerF23F0A18, BIReportingQuickSightQuickSightCustomResource98537A5B, BIReportingEtlGlueConfigurationJobTriggerF0172159, FrontEndHostingDistributionToS3CloudFrontDistribution6DBBF508]. Rollback requested by user.
```

The root cause of the failure is `BIReportingQuickSightQuickSightCustomResource` (probably around [this line](https://github.com/awslabs/machine-downtime-monitor-on-aws/blob/main/source/cdk-infrastructure/lib/bi-reporting/quicksight/quicksight-construct.ts#L87) in CDK):

![image](https://user-images.githubusercontent.com/24555667/128957574-116435fa-dcbe-4d8b-abfd-16a40de61213.png)

The CloudWatch Logs stream that the above message is referring to says:

`AccessDeniedException: Insufficient permission to access the manifest file`. This issue is addressed on the documentation: https://docs.aws.amazon.com/solutions/latest/machine-downtime-monitor-on-aws/troubleshooting.html

I changed the `aws-quicksight-service-role-v0`'s inline policy (`QuickSightS3ReadOnly`) but it still ends up in the same error.

**Comment by ShutoAraki** [comment]
I can use QuickSight by opting out of using QuickSight on CFn stack creation and then manually import the data from Athena, if that information helps.

**Comment by gattasrikanth** [comment]
Can you try the below:

Go to the AWS IAM console. Choose Roles in the left menu pane. Search `aws-quicksight-service-role-v0` or `aws-quicksight-s3-consumers-role-v0`, and choose the role. Choose **AWSQuickSightS3Policy** or **AWSQuickSightS3ConsumerPolicy** at **Permissions** tab. Choose **Edit** policy, choose **JSON**, and put the below policy:
```
{
  "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:ListAllMyBuckets",
                "s3:ListBucket",
                "s3:GetObject",
                "s3:GetObjectVersion"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::*"
            ]
        }
    ]
}
```

**Comment by ShutoAraki** [comment]
I changed my `quicksight-s3-consumers-role-v0`'s **AWSQuickSightS3ConsumerPolicy** to that and it worked! Thank you!!
